// This file is automatically generated. Do not edit it directly.

import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// 1️⃣ Leer variables de entorno
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

// 2️⃣ Log de comprobación (temporal, útil ahora)
console.log("ENV CHECK =>", {
  hasUrl: !!SUPABASE_URL,
  urlPreview: SUPABASE_URL ? SUPABASE_URL.slice(0, 25) + "..." : null,
  hasKey: !!SUPABASE_PUBLISHABLE_KEY,
  keyPreview: SUPABASE_PUBLISHABLE_KEY ? SUPABASE_PUBLISHABLE_KEY.slice(0, 15) + "..." : null,
});

// 3️⃣ Crear cliente Supabase
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
